### ISSUE TITLE
Request for Comment : Addition of Geometry Courses in Core and Advanced OSSU/Math

### ISSUE THREAD

**Issue by aayushsinha0706** [ossu/math#21]
**Problem:**
OSSU Math does not introduce geometry in its core curriculum and does not recommend any texts/courses in its Advanced Math 

**Duration:**
January 12, 2022.

**Background:**
OSSU promises the equivalent of education an undergraduate education in Mathematics. In order to evaluate our recommended courses, we use the [CUPM 2015 guideline](https://www.maa.org/node/790342) that specifies number of mathematical areas a student should cover.

Let us visit [Geometry ](https://www.maa.org/sites/default/files/Geometry.pdf) section of CUPM 2015.

CUPM 2015 basic recommendations state that
>Every mathematics department should offer at least one undergraduate course devoted primarily to geometry. There will probably never be a consensus on what that course should cover. However, in Section 6 we offer sample syllabi for some of the many valid course choices that institutions might make. We also outline in Section 4 some of the important issues institutions should consider as they decide which geometry course, or courses, to offer.

>Reference : CUPM 2015 Page 1

Let us jump to Section 6 for sample syllabi 

> One such course is **A Survey of Geometries** This course aims for breadth, while sacrificing some depth. It assumes that students do remem- ber some of the Euclidean geometry they learned in high school. The level of rigor is purposefully sacrificed in order to develop intuition and to cover some of the breadth of geometry.

Topics covered under this suggestion
 - Euclidean geometry
 - Analytic geometry
 - Hyperbolic geometry
 - Spherical geometry
 - Transformations
 - Symmetries
 - Projective geometry

>Reference : CUPM 2015 Geometry Page 11

I suggest this book [Euclidean Plain and Its Relatives](https://arxiv.org/pdf/1302.1630v19.pdf) for such a course

>This book is meant to be rigorous, conservative, elementary, and mini- malist. At the same time, it includes about the maximum what students can absorb in one semester.Approximately one-third of the material used to be covered in high school, but not anymore.
The present book is based on the courses given by the author at the Pennsylvania State University as an introduction to the foundations of geometry. The lectures were oriented to sophomore and senior university students. These students already had a calculus course. In particular, they are familiar with real numbers and continuity. It makes it possible to cover the material faster and in a more rigorous way than it could be done in high school.

If we look at the Table of Contents of the book it covers
- Euclidean Geometry
- Hyperbolic Geometry
- Spherical Geometry
- Projective Geometry etc.

This book perfectly suits what above CUPM course suggests and can act as a foundation for advanced geometry courses.

**Geometry Advanced Courses/Books**

Upon reviewing the CUPM 2015. The resources to cover advanced courses in Advanced Geometry

To Learn Euclidean Geometry the book by Sir Euclid 's [Euclid Elements](https://mathcs.clarku.edu/~DJoyce/java/elements/elements.html) is best in itself. A argument that can be raised here 
**Is It still worth it to study Euclid Elements today?** To support this argument I suggest to read this [quora answer](https://www.quora.com/Is-Euclids-Elements-still-worth-learning-What-book-s-can-you-recommend-for-Euclidean-geometry)

For Non-Euclidean Geometry I suggest this book [Geometry with an Introduction to Cosmic Topology](https://mphitchman.com)

>What CUPM suggests
Non-Euclidean geometries. The discovery of non-Euclidean geometries was a foundation-shaking event in the history of mathematics. All mathematics majors, with the possible exception of those specializing in certain applied subdisciplines, should know about these developments and how they changed the human understanding of the relationship between mathematics and the real world. This could be part of a geometry course or it could be studied in some other course (such as a history of mathematics course). Ideally, students should know the examples of hyperbolic, elliptic, and spherical geometries.

> About the book
From the preface:
 Geometry with an Introduction to Cosmic Topology offers an introduction to non-Euclidean geometry through the lens of questions that have ignited the imagination of stargazers since antiquity. What is the shape of the universe? Does the universe have an edge? Is it infinitely big? This text is intended for undergraduate mathematics and physics majors who have completed a multivariable calculus course and are ready for a course that practices the habits of thought needed in advanced courses of the undergraduate mathematics curriculum. The text is also particularly suited to independent study, with essays and other discussions complementing the mathematical content in several sections.
Contents
An Invitation to Geometry
The Complex Plane
Transformations
Geometry
Hyperbolic Geometry
Elliptic Geometry
Geometry on Surfaces
Cosmic Topology

Also the [review](https://www.maa.org/press/maa-reviews/geometry-with-an-introduction-to-cosmic-topology) by MAA calls it **“a masterfully written textbook.”**

Another course suggested by CUPM 2015 is Differential Geometry

>6.7 Differential geometry
The undergraduate differential geometry course should include theoretical and computational com- ponents, intrinsic and extrinsic viewpoints, and numerous applications:
18
• Geometry of curves in space, including the Frenet frame
• Theory of surfaces, including parameterizations, first and second fundamental forms, curva-
ture and geodesics
• The concluding part of the course could be a focus that depends on the interest of the instructor and students, such as the Gauss-Bonnet Theorem, the theory of minimal surfaces, or the geometry of space-time with applications to general relativity.
Ideally a course in differential geometry allows students to see the connections between such topics as calculus, geometry, spatial visualization, linear algebra, differential equations, and complex variables, as well as various topics from the sciences, including physics. The course may serve as an introduction to these topics or a review of them. The course is not only for mathematics majors—it encompasses techniques and ideas relevant to many students in the sciences, such as physics and computer science.

For this topic I suggest this book 
[A Course in Differential Geometry](https://arxiv.org/pdf/math/0412421.pdf) by SHARIPOV R.A. 

What book says
> **This book is a textbook for the basic course of differential geometry. It is recommended as an introductory material for this subject**. **This book is devoted to the first acquaintance with the differential geometry.** Therefore it begins with the theory of curves in three-dimensional Euclidean space E. Then the vectorial analysis in E is stated both in Cartesian and curvilinear coordinates, afterward the theory of surfaces in the space E is considered. The newly fashionable approach starting with the concept of a differentiable manifold, to my opinion, is not suitable for the introduction to the subject. In this way too many efforts are spent for to assimilate this rather abstract notion and the rather special methods associated with it, while the the essential content of the subject is postponed for a later time. I think it is more important to make faster acquaintance with other elements of modern geometry such as the vectorial and tensorial analysis, covariant differentiation, and the theory of Riemannian curvature. The restriction of the dimension to the cases n = 2 and n = 3 is not an essential obstacle for this purpose. The further passage from surfaces to higher-dimensional manifolds becomes more natural and simple.

>Topics Covered by the book follows a lot what CUPM 2015 suggests.

**Proposal**

Add the above texts as following

### Geometry

Courses | Duration | Effort | Prerequisites
:-- | :--: | :--: | :--:
[Euclid Plain and Its Relatives](https://arxiv.org/pdf/1302.1630v19.pdf) | 20 weeks | 3-5 hours/week | Elementary Set Theory and Calculus 1C

### Geometry

Courses | Duration | Effort | Prerequisites
:-- | :--: | :--: | :--:
[Euclid Elements](https://mathcs.clarku.edu/~DJoyce/java/elements/elements.html) | 13 weeks | 6-8 hours/week | Mathematical Maturity 
[Geometry with an Introduction to Cosmic Topology](https://mphitchman.com) | 16 weeks | 7-8 hours/week | Multivariable Calculus
[Differential Geometry](https://arxiv.org/pdf/math/0412421.pdf) | 8 weeks | 4-5 hours/week | Multivariable Calculus

**Comment by waciumawanjohi** [comment]
> Every mathematics department should offer at least one undergraduate course devoted primarily to geometry.

I am concerned that we may have too many courses in Core Mathematics rather than too few. A statement that every university should offer an option is very different from an expectation that every university student should take a course.  The guidance for OSSU Core Math is:

"All OSSU Math students need to take all of these courses."

I took a moment to look at the math requirements at MIT, Stanford and Princeton. (To be clear, this analysis by comparison is one that I hope OSSU can avoid, as rationalizing a standard from dozens of examples of university curricula is much more difficult than following an established set of standards) Those departments have few courses that are required for all students in the department. Princeton is the only of the three that requires students take a course in Geometry (and even there the course can be substituted by topology or discrete math).

This state of affairs, where students have much wider latitude in choice than in other disciplines, seems reflected in the CUPM 2015, which is much less didactic about topics every graduate must have mastered.

I wonder if in the long term OSSU Math should move to a model that expects a very small set of courses recommended for all students (Core Math), a set of courses from which students must select at least N (Advanced Math?) and a further set of elective courses (Elective Math)?

Setting aside that rumination to focus on this RFC:

I don't see evidence that Geometry should be included in Core Math. I do see provided evidence that we should include Geometry resources in Advanced Math. I see evidence that the resources recommended are of high quality and I look forward to further discussion of them.

**Comment by spamegg1** [comment]
@aayushsinha0706 "Euclid Plane and its Relatives" and "Geometry with and Introduction to Cosmic Topology" are great sources. They are both well-written, modern, short but not too short, have a ton of figures, and decent amount of doable exercises. Excellent finds!

<details>
<summary>I don't think I can support reading Euclid's Elements as a direct source of learning.</summary>

It's true that it's an incredibly important historical text. But it is more appropriate for a History of Mathematics elective course. 1) It is written almost completely in text, without any of the modern notation and algebraic conventions we are used to, 2) as such, it would require a ton of guidance for a modern mind to decipher and understand (the website linked provides some of that but it's nowhere sufficient), 3) not all of the 13 books are about geometry, and 4) it would be a repetition of the axiomatic approach already covered in "Euclid Plane and its Relatives".
</details>

<details>
<summary>The "Course on Differential Geometry" text is not very good.</summary>

 It's been translated from Russian, it's a bit dense and hard to understand, it packs a ton of material into about 130 pages, it goes into tensor fields and tensor products way too early (Russian texts like to do that in other fields too, like Operator Theory), and it has no exercises whatsoever (searching for the word "exercise" yields 0 results). Look at this:
![tensors](https://user-images.githubusercontent.com/4255997/145784112-cf28b691-eee3-45ab-9629-176b8920b277.png)

This is already happening on Page 21. It also adds a lot of other implicit prerequisites to learning Diff Geo, such as the theory of quadratic forms and very strong abstract algebra (group and field theory). The Russian school of math prefers doing it this way. They use tensor fields as the basic machinery for a lot of different kinds of math. 

The book makes no attempt to indicate what the prerequisites are, because the Preface says that it is the third in a series of 3 books that are meant to be used in sequence (the first book was never written apparently!). This notation and the machinery will be alien to someone who only finished Multivariable Calculus. It's possible to avoid tensor products, group and field theory ENTIRELY and build DIff Geo on other, much simpler machinery of Multivariable Calculus (searching for the word "tensor" in the textbook I mention below yields 0 results).
</details>


<details>
<summary>This is the go-to textbook for Diff Geo around the world:</summary>

[Differential Geometry of Curves and Surfaces by Manfredo do Carmo](https://www.amazon.com/Differential-Geometry-Curves-Surfaces-Mathematics/dp/0486806995)

This is what I used in my undergrad, and it is also used by the [MIT](https://ocw.mit.edu/courses/mathematics/18-950-differential-geometry-fall-2008/) [courses](https://dspace.mit.edu/bitstream/handle/1721.1/49826/18-950Spring-2005/OcwWeb/Mathematics/18-950Spring-2005/CourseHome/index.htm). Just to put things in context, this book reaches the Gauss-Bonnet theorem in 450 pages whereas the above text does in 130. It has tons of figures and exercises, to which solutions can be found online.

Unfortunately it is not free, but at least it is published by the "affordable math textbook publisher" Dover. I've been looking into free alternatives but could not find any satisfactory texts so far. The best I've found is [this](https://people.math.wisc.edu/~robbin/Do_Carmo/diffgeo.pdf) which the professor says he prefers to the do Carmo text. But this also starts out with Manifolds, some tensors, and a ton of abstract algebra, such as the General Linear group `GL(n, R)` and Special Linear group `SL(n, R)` in `n`-dimensions (these are not even covered by the Core AA courses). The do Carmo text has absolutely no prerequisites other than Multivariable Calculus (the definition of "manifold" occurs for the first time on page 431).
</details>

@waciumawanjohi To address your rumination, usually there is one Geometry course in undergraduate curricula, usually a 3rd or 4th year elective such as Differential Geometry or some other variant. Euclidean plane geometry is assumed to have been covered in high school, and the axiomatic approach to plane geometry is usually covered in a 1st year proofs/discrete math course. ***My recommendation would be:*** either figure out a good free resource for Diff Geo (or make a compromise with the Dover book, in which case we could even use the MIT courses) and use that as _the only Geometry course_, or use "Geometry with an Introduction to Cosmic Topology" _as the only Geometry course._  (I'd like to point out that Diff Geo is my favorite subject of all time ever in anything, so I'm making a **big compromise** here! Depending on what we will do for Topology, some basic Diff Geo might be covered by the Topology course. Munkres has some stuff on it.)

**Comment by aayushsinha0706** [comment]
@waciumawanjohi Ok upon reviewing CUPM 2015 . I guess I can be fine with not a compulsory geometry course.

>I wonder if in the long term OSSU Math should move to a model that expects a very small set of courses recommended for all students (Core Math), a set of courses from which students must select at least N (Advanced Math?) and a further set of elective courses (Elective Math)?

According to me OSSU in the long term should make Core Math and breadth requirement of Advanced Math compulsory for all students and allow students to take further electives if they want to. Core Math in itself is way too light to be called an equivalent mathematics major. 

For Geometry courses
I am not in the support of introducing just only one course in geometry. Students should be given choice between A survey of geometries, Non-Euclidean Geometry and Differential geometry.

For Euclidean Geometry Euclid's elements is still like a holy book for the subject. But I can understand why @spamegg1 don't recommend learning euclidean geometry directly from it.

From Differential Geometry I did found a playlist on from Professor NJ Wilderberg from UNSW Sydney

We can offer them as supplementary lectures, same as we did with Analysis.

**Comment by aayushsinha0706** [comment]
While @spamegg1  mentioned about Topology I am having a different plan to introduce topology as a separate advanced maths course in a different RFC

For Topology. I am planning to introduce [Topology without tears](https://www.topologywithouttears.net). It has some really good reviews on [Goodreads](https://www.goodreads.com/en/book/show/17736103-topology-without-tears). And also author of the book made a really good effort to make it freely available.

**Comment by waciumawanjohi** [comment]
@aayushsinha0706 Your proposal has responded to all of the comments offered and there have been no new comments. I encourage you to make a PR for the changes you propose [here](https://github.com/ossu/math/issues/21#issuecomment-992667294) and I will merge it in.

**Comment by waciumawanjohi** [comment]
Closed by #23
