### ISSUE TITLE
Logic Course to Evaluate

### ISSUE THREAD

**Issue by uRSTEnzY** [ossu/math#9]
I think we should investigate using https://www.coursera.org/learn/logic-introduction as the required logic course.  It's a little more focus on generic logic vs math logic, but I think it still applies.  I'd love to hear some thoughts.

**Comment by spamegg1** [comment]
*(I should mention that I have extensively studied everything under the Logic Study guide, and far more, in my past.)*

I have fully completed the Stanford course, solved all the problems. I was [pretty harsh to it](https://github.com/spamegg1/reviews#logic), I think it's quite bad. It's certainly quite inferior to the resources below. I would not recommend it to anyone. I followed some recent changes to it on Coursera in the last few months, and they still haven't fixed the broken Resolution proof tools. (I have also read through the longitudinal evaluation, which seems to be more about feedback from classrooms that used it as a resource, not the online course itself.) 

<details>

<summary>On Tarskian vs. Herbrand semantics</summary>

I was "raised on" Tarskian semantics, but later studied Herbrand semantics too (which my academic advisors would call "syntactical thinking"), which I thought was fine. However I think Tarskian semantics are more intuitive and grounded, because they force your mind to tie logical sentences "down to earth" to a model, a mathematical object which has a set, elements, numbers and so on. This is tremendously helpful, especially if you have to study not just formal proofs, but other branches of Logic such as Model Theory, Set Theory and Gödel Incompleteness, as I did. Also Tarskian semantics connect Logic to all other areas of mathematics much more easily. Take a look at ["Reverse Mathematics"](https://www.amazon.com/Subsystems-Second-Order-Arithmetic-Perspectives/dp/0521150140/)

I've tutored some learners taking the Stanford course (Herbrand semantics) who really struggled with the concepts of Satisfiability, Logical Implication and so on, because they could not create a mental mapping between a "universe of formulas" and a universe of objects, which "satisfy" those formulas as properties. So it looked like meaningless symbol pushing to them. Although this is more on the quality of the Stanford course, rather than Herbrand semantics.

Tarskian semantics are much more difficult to set up initially (requires a lot of "machinery"), you pay a much bigger price up front, but it pays off in the long term. Although this is probably more of a theoretical debate, and I should admit bias as Tarski happens to be my mathematical ancestor.
</details>

I have read through the other suggested sources: 

The ForallX project strikes a good balance between verbosity and brevity, between beginner topics and advanced topics. It's quite friendly at the beginning sections, covering the basics, but it does get difficult later on, especially the last two sections on Modal Logic and Metatheory. It has a similar approach to the Stanford course, uses Natural Deduction and linear proofs that are written vertically, but uses Tarskian semantics for first order logic. It is a bit light on the number of exercises.

I've known about the Logic Matters site for years now. The Logic Matters book "Introduction to Formal Logic" is quite good but also quite verbose (like me, I guess that's a logician thing :) ), which I suppose could be taken as a good thing or a bad thing. It spends quite a long time on, and delves into details of, the basics and fundamentals. And it has... A LOT OF EXERCISES. It's like the exact opposite of the Stanford course in that way. However it's quite shallow. It barely finishes quantifier logic in about 400 pages. It does not cover the later, mid-advanced topics of ForallX. I think it might be very good for those learners who really struggle with logical concepts and require in-depth explanations, but also very bad for those who get lost in long verbose explanations.

Neither of these two resources cover Resolution and Unification from the Stanford course, though.

Logic in Action has a little bit of everything. In about 400 pages or so it covers many many topics, including Modal Logics. It even has "applications", like a chapter dedicated to basic Game Theory, and one on Computation, even touching upon Prolog/Resolution/Unification (like Stanford). It stands as a very broad survey-like text that does not delve deeply into its topics. It's definitely the most "real world" out of all. It also uses the totally awesome approach of modeling proofs as *games that are played on trees* between a "prover" and a "falsifier", which is what I've learned from my own advisor. But each chapter is quite short and very light on exercises.

**My recommendations:** I would recommend the ForAllX project as the best compromise/most balanced resource for everyone, while recommending the Logic Matters resource to those who are struggling and need more exercises and supplementary materials on the fundamentals. I'd recommend LIA to those who are adventurous, already somewhat strong in mathematical disciplines, and who don't mind filling in the blanks themselves, while desiring to cover a broad range of topics.

**Comment by waciumawanjohi** [comment]
1. @spamegg1 it is always great to read your contributions. Good to hear from you.
2. Let's do it. The issue has been open for over a year! I'm very comfortable with the ForAllX recommendation. I'm going to make that addition now. I don't have a plan for how to add the "gentler route" Logic Matters and the "adventurous" Logic In Action. I invite Pull Requests with ideas about how to best format those offerings.
